config:
  RequiredTwerkCount: 10 # default: 10
  RangeForShifting: 5 # default: 5
  GrowingParticle: true 
  MushroomTreesOnlyOnMycelium: true
Trees:
  OakTree: true
  SpruceTree: true
  BirchTree: true
  AcaciaTree: true
  JungleTree: true
  BigOakTree: false # developing
  BigSpruceTree: true
  BigJungleTree: true
  DarkOakTree: true
  RedMushroomTree: true
  BrownMushroomTree: true