config:
  RequiredTwerkCount: 2 # default: 10
  RangeForShifting: 10 # default: 5
  GrowingParticle: true 
  MushroomTreesOnlyOnMycelium: true
Trees:
  OakTree: true
  SpruceTree: true
  BirchTree: true
  AcaciaTree: true
  JungleTree: true
  BigOakTree: false
  BigSpruceTree: false
  BigJungleTree: false
  DarkOakTree: false
  RedMushroomTree: false
  BrownMushroomTree: false