name: TreeTwerk
authors: [Cazcez, mfnalex, RaiTaki]
dev-url: http://github.com/Chereza/TreeTwerk-remastered
main: treetwerk.main.Main
version: 0.1.3
api-version: 1.13

commands:
  TreeTwerk:
    description: it does what it needs to do
